version: '2'
services:
 zabbix-java-gateway:
  image: "${Zabbix_Java}"
  ports:
   - "10052:10052"
  container_name: zabbix-java-gateway
  environment:
   TZ: ${TZ}
  tty: true
  networks:
   - zbx-net
  depends_on:
   - mysql-server
 zabbix-server:
  image: "${Zabbix_Server}"
  container_name: zabbix-server-mysql
  ports:
   - "10051:10051"
  environment:
   DB_SERVER_HOST: ${DB_SERVER_HOST}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   ZBX_JAVAGATEWAY: ${ZBX_JAVAGATEWAY}
   TZ: ${TZ}
  volumes:
   - ${DATA_PATH}/alertscripts:/usr/lib/zabbix/alertscripts:ro
   - ${DATA_PATH}/externalscripts:/usr/lib/zabbix/externalscripts:ro
   - ${LOCAL_TIME}:${LOCAL_TIME}:ro
  networks:
   - zbx-net
  links:
   - mysql-server:mysql-server
   - zabbix-java-gateway:zabbix-java-gateway
  depends_on: 
   - zabbix-java-gateway
 zabbix-web-nginx:
  image: "${Zabbix_WebServer}"
  container_name: zabbix-web-nginx
  ports:
   - "80:80"
  environment:
   DB_SERVER_HOST: ${DB_SERVER_HOST}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   PHP_TZ: ${PHP_TZ}
   TZ: ${TZ}
  volumes:
   - ${DATA_PATH}/fonts/DejaVuSans.ttf:/usr/share/fonts/ttf-dejavu/DejaVuSans.ttf:ro
   - ${LOCAL_TIME}:${LOCAL_TIME}:ro
  links:
   - mysql-server:mysql-server
   - zabbix-server:zabbix-server
  networks:
   - zbx-net
  depends_on: 
   - zabbix-server
 mysql-server:
  image: "${Mysql_Server}"
  container_name: mysql_server
  environment:
   DB_SERVER_HOST: ${DB_SERVER_HOST}
   MYSQL_DATABASE: ${MYSQL_DATABASE}
   MYSQL_USER: ${MYSQL_USER}
   MYSQL_PASSWORD: ${MYSQL_PASSWORD}
   MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
   TZ: ${TZ}
  command: [mysqld, --character-set-server=utf8, --collation-server=utf8_bin]
  volumes:
   - ${LOCAL_TIME}:${LOCAL_TIME}:ro
  networks:
   - zbx-net

networks:
  zbx-net:
